name: setup

description: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16.18.x"
        cache: npm
    - name: Install packages
      run: npm install
      shell: bash
    - name: Install snarkjs
      shell: bash
      run: npm install -g snarkjs
    - name: Setup cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
      name: Clone circom repo
      shell: bash
      run: git clone https://github.com/iden3/circom.git
    - name: ⚡ Cache
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          circom
        key: ${{ runner.os }}-cargo
    - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
      name: Install circom
      shell: bash
      working-directory: circom
      run: |
        cargo build --release
        cargo install --path circom
    - name: ⚡ Cache circom
      id: cache-circom
      uses: actions/cache@v3
      with:
        path: |
          circuits/outputs
        key: |
          ${{ runner.os }}-circom-${{ hashFiles('**/Withdraw.circom') }}
          ${{ runner.os }}-circom-${{ hashFiles('**/Verifier.circom') }}
    - if: ${{ steps.cache-circom.outputs.cache-hit != 'true' }}
      name: Generate trusted setup
      shell: bash
      run: |
        ./circuits/helper.sh
