name: setup

description: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16.18.x"
        cache: npm
    - name: Install packages
      run: npm install
      shell: bash
    - name: Setup cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Clone circom repo
      shell: bash
      run: git clone https://github.com/iden3/circom.git
    - name: ⚡ Cache
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          circom/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install circom
      shell: bash
      working-directory: circom
      run: |
        cargo build --release
        cargo install --path circom
    - name: Install snarkjs
      shell: bash
      run: npm install -g snarkjs
    - name: ⚡ Cache circom
      id: cache-circom
      uses: actions/cache@v3
      with:
        path: |
          circuits/outputs
        key: |
          ${{ runner.os }}-circom-${{ hashFiles('**/Withdraw.circom') }}
          ${{ runner.os }}-circom-${{ hashFiles('**/Verifier.circom') }}

    - if: ${{ steps.cache-circom.outputs.cache-hit != 'true' }}
      name: Generate trusted setup
      shell: bash
      run: |
        ./circuits/helper.sh

    - if: ${{ steps.cache-circom.outputs.cache-hit != 'true' }}
      name: Update Verifier
      uses: test-room-7/action-update-file@v1
      secrets:
        secret: ${{ secrets.GITHUB_TOKEN }}
      with:
        file-path: contracts/utils/Verifier.sol
        commit-msg: Update resources
