name: setup

description: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16.18.x"
        cache: npm
    - name: Install packages
      run: npm install
      shell: bash
    - name: Install snarkjs
      shell: bash
      run: npm install -g snarkjs
    - name: ⚡ Cache circom
      id: cache-circom
      uses: actions/cache@v3
      with:
        path: |
          circuits/outputs
          circom-linux-amd64
        key: |
          ${{ runner.os }}-circom-${{ hashFiles('**/Withdraw.circom') }}
    - if: ${{ steps.cache-circom.outputs.cache-hit != 'true' }}
      name: Generate trusted setup
      shell: bash
      run: |
        ./circuits/helper.sh
