name: "checks"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Caching Circuits
        id: cache-circuits
        env:
          cache-name: cache-circuits
        uses: actions/cache@v3
        with:
          path: |
            ./circuits
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./circuits') }}

      - name: Circuits compiling
        if: ${{ steps.cache-circuits.outputs.cache-hit != 'true' }}
        run: ./circuits/helper.sh

      - name: Compile
        run: npx hardhat compile --force

      - name: Run tests
        run: npm run test

      - if: ${{ steps.cache-circuits.outputs.cache-hit != 'true' }}
        name: Update Verifier
        uses: test-room-7/action-update-file@v1
        with:
          file-path: contracts/utils/Verifier.sol
          commit-msg: Update Verifier cotract
          github-token: ${{ secrets.PUSH_TOKEN }}
